### ISSUE TITLE
Ability to specify TestCafe Live in the runner class

### ISSUE THREAD

**Issue by rquellh** [DevExpress/testcafe-live#12]
### Are you requesting a feature or reporting a bug?
Feature

### What is the current behavior?
For TestCafe users that are using CucumberJS to drive tests it's difficult to use TestCafe Live. I've already tried using [concurrently](https://www.npmjs.com/package/concurrently) to run Cucumber and TestCafe-Live in parallel, but I get the following error.

```
Stopping TestCafe Live...
[0] C:\Users\rquellhorst\Desktop\testcafe-cucumber\node_modules\testcafe-live\lib\index.js:38
[0] process.stdin.setRawMode(true);
[0]               ^
[0]
[0] TypeError: process.stdin.setRawMode is not a function
[0]     at Object.<anonymous> (C:\Users\rquellhorst\Desktop\testcafe-cucumber\node_modules\testcafe-live\lib\index.js:38:15)
[0]     at Module._compile (module.js:635:30)
[0]     at Object.Module._extensions..js (module.js:646:10)
[0]     at Module.load (module.js:554:32)
[0]     at tryModuleLoad (module.js:497:12)
[0]     at Function.Module._load (module.js:489:3)
[0]     at Module.require (module.js:579:17)
[0]     at require (internal/module.js:11:18)
[0]     at Object.<anonymous> (C:\Users\rquellhorst\Desktop\testcafe-cucumber\node_modules\testcafe-live\bin\testcafe-live.js:5:1)
[0]     at Module._compile (module.js:635:30)
[0] npm ERR! code ELIFECYCLE
[0] npm ERR! errno 1
[0] npm ERR! testcafe-cucumber@0.0.1 testcafe-live: `testcafe-live.cmd chrome test.js`
[0] npm ERR! Exit status 1
[0] npm ERR!
[0] npm ERR! Failed at the testcafe-cucumber@0.0.1 testcafe-live script.
```

### What is the expected behavior?
It would be nice to specify that you want to use TestCafe-Live in the runner class. 

### How would you reproduce the current behavior (if this is a bug)?
You could pull my [repo](https://github.com/rquellh/testcafe-cucumber) to see my code.

#### Provide the test code and the tested page URL (if applicable)
NA

### Specify your

* operating system: Windows 10.0.0
* testcafe version: 0.19.0
* testcafe-live version: 0.1.3
* node.js version: 0.8.3

**Comment by AndreyBelym** [comment]
I close this issue because now you can use the [LiveModeRunner class](https://devexpress.github.io/testcafe/documentation/using-testcafe/programming-interface/livemoderunner.html) introduced in `testcafe@1.0.0`.
