### ISSUE TITLE
unhandled promise rejection during start with newest testcafe@0.21.1

### ISSUE THREAD

**Issue by nitschSB** [DevExpress/testcafe-live#25]
testcafe-live@0.1.3

$ npm --version
5.7.1

$ node --version
v8.12.0

Windows 7

```
$~\tmp\systemtest-testcafe-example>npm run test-chrome:live --verbose
npm info it worked if it ends with ok
npm verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Users\\example\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'run',
npm verb cli   'test-chrome:live',
npm verb cli   '--verbose' ]
npm info using npm@5.7.1
npm info using node@v8.12.0
npm verb run-script [ 'pretest-chrome:live',
npm verb run-script   'test-chrome:live',
npm verb run-script   'posttest-chrome:live' ]
npm info lifecycle testcafe-test@1.0.0~pretest-chrome:live: testcafe-test@1.0.0
npm info lifecycle testcafe-test@1.0.0~test-chrome:live: testcafe-test@1.0.0

> testcafe-test@1.0.0 test-chrome:live C:\Users\example\test-puppeteer\tmp\systemtest-testcafe-example
> testcafe-live --speed 1 --assertion-timeout 1000 --selector-timeout 10000 --page-load-timeout 10000 chrome tests/*.js

(node:5312) UnhandledPromiseRejectionWarning: Error: watch tests/*.js ENOENT
    at FSWatcher.start (fs.js:1382:19)
    at Object.fs.watch (fs.js:1408:11)
    at FileWatcher.addFile (C:\Users\example\test-puppeteer\tmp\systemtest-testcafe-example\node_modules\testcafe-live\lib\file-watcher\index.js:53:38)
    at FileWatcher.files.forEach.f (C:\Users\example\test-puppeteer\tmp\systemtest-testcafe-example\node_modules\testcafe-live\lib\file-watcher\index.js:18:33)
    at Array.forEach (<anonymous>)
    at new FileWatcher (C:\Users\example\test-puppeteer\tmp\systemtest-testcafe-example\node_modules\testcafe-live\lib\file-watcher\index.js:18:15)
    at Controller._initFileWatching (C:\Users\example\test-puppeteer\tmp\systemtest-testcafe-example\node_modules\testcafe-live\lib\controller.js:52:29)
    at Controller.init (C:\Users\example\test-puppeteer\tmp\systemtest-testcafe-example\node_modules\testcafe-live\lib\controller.js:24:14)
    at tcArguments.parse.then (C:\Users\example\test-puppeteer\tmp\systemtest-testcafe-example\node_modules\testcafe-live\lib\index.js:16:28)
    at <anonymous>
(node:5312) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5312) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by shanshanyang** [comment]
experience the same error since updating testcafe to v0.22.0

testcafe-live@0.1.3

$ npm --version
5.8.0

$ node --version
v8.11.1

macOS Sierra

**Comment by AndreyBelym** [comment]
I can't reproduce the issue with Live mode integrated into `testcafe@1.0.0`: [TestCafe 1.0.0 Released: Live mode](https://devexpress.github.io/testcafe/blog/testcafe-v1-0-0-released.html#live-mode-3215). If you still can reproduce with `testcafe@1.0.0`, please create a [new bug report](https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md) in the main TestCafe repository.
